# use with REST Client in VS Code

@host = http://localhost:5173

# this hook URL is for the demo test user
@user_id = a2dc5f10-5123-45ec-bf8c-1076c47681ff
@username = user@spammerdomain.com
@password = nebula-aid-harry

@hooksite = {{host}}/h/{{user_id}}

###
# server status
###

# @name status
GET {{host}}/status

###


###
# GET
###

# @name get_simple
GET {{hooksite}}?param1=hello&param2=world+%26+friends&rand={{$randomInt 200 800}}
X-Forwarded-For: 1.2.3.4

###

###
# POST
###

# @name post_json
POST {{hooksite}}
Content-type: application/json
X-Forwarded-For: 2001:db8:85a3::8a2e:370:7334

{
    "hello": "world",
    "randomness": {{$randomInt 20000 80000}}
}

###

# @name post_plain
POST {{hooksite}}?foo=bar
Content-type: text/plain
X-Forwarded-For: 2001:db8:85a3::8a2e:370:7334

Hello, world & friends!

###

# @name post_form
POST {{hooksite}}
Content-type: application/x-www-form-urlencoded

hello=world+%25+friends

###

# @name manual_login
# cookies are kept in $HOME/.rest-client/cookies.json
POST {{host}}/login
Content-type: application/x-www-form-urlencoded

email={{username}}&password={{password}}

###

# if logout is called with GET, it does immediate redirect and load of home page, which is ugly
# in this test script.
# @name manual_logout
POST {{host}}/logout

###
